### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [avocadoras/gather-phase-1-start#1]
The required route, database and user interaction tests are all correct. running npm test showed that all the tests ran and passed successfully. The features on the app also worked as it should. The written tests covered all the features to be tested. Great job. We see where you added additional tests for the update button. The update button should be targeted to the button being clicked as `.button.update-button`. For further help, contact a Express and/or TDD adviser at http://codecademy.com.

**Comment by avocadoras** [comment]
@mp1pro for some reason webdriver cannot locate the button... says it doesn't exist even though I can print the HTML with browser object before clicking and verify that the button is there.
